=== celeron1ghz/acceptessa-checklist/client/config/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Schema",
    "definitions": {
        "Schema": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "space": {
                    "$ref": "#/definitions/Space"
                },
                "tweet": {
                    "$ref": "#/definitions/Tweet"
                },
                "vertical_syms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/VerticalSym"
                    }
                },
                "horizontal_syms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/HorizontalSym"
                    }
                }
            },
            "required": [
                "space",
                "tweet"
            ],
            "title": "Schema"
        },
        "HorizontalSym": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "sym": {
                    "type": "string"
                },
                "top": {
                    "type": "integer"
                },
                "idx": {
                    "type": "integer"
                },
                "lefts": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            },
            "required": [
                "lefts",
                "sym",
                "top"
            ],
            "title": "HorizontalSym"
        },
        "Space": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "width": {
                    "type": "integer"
                },
                "height": {
                    "type": "integer"
                }
            },
            "required": [
                "height",
                "width"
            ],
            "title": "Space"
        },
        "Tweet": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "url": {
                    "type": "string"
                },
                "hashtags": {
                    "type": "string"
                },
                "related": {
                    "type": "string"
                }
            },
            "required": [
                "hashtags",
                "related",
                "url"
            ],
            "title": "Tweet"
        },
        "VerticalSym": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "sym": {
                    "type": "string"
                },
                "left": {
                    "type": "integer"
                },
                "idx": {
                    "type": "integer"
                },
                "tops": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            },
            "required": [
                "left",
                "sym",
                "tops"
            ],
            "title": "VerticalSym"
        }
    }
}

=== celeron1ghz/acceptessa-checklist/client/config/sampledata.json
{
  "space": {
    "width": 29,
    "height": 62
  },
  "tweet": {
    "url": "http://yutoriou.com/comicou/",
    "hashtags": "コミック王",
    "related": "yutoriou"
  },
  "vertical_syms": [
    {
      "sym": "来賓",
      "left": 74,
      "tops": [
        129,
        194,
        260,
        326,
        455,
        521,
        586,
        652
      ]
    }
  ],
  "horizontal_syms": [
    {
      "sym": "来賓",
      "top": 66,
      "idx": 9,
      "lefts": [
        463,
        529
      ]
    }
  ]
}
